### ISSUE TITLE
Slimes a bit OP

### ISSUE THREAD

**Issue by Suhayll** [CHOMPstation/CHOMPstation#143]
I guess we can all agree that slimes might be a weee bit on the OP side. 
They seem practically immune to everything but water based attacks such as fire extinguisher.
I guess a few of you had the misfortune of slipping on your own wet floors when fighting slimes.
They can easily knock down their target causing them to drop everything on them, and deal "perma" damage in the form of genetic damage that makes the victim undifibable. In medical view. If you die with a bit too much genetic damage. They can't save you and have to resleeve. Point is, there is no way to lower genetic damage after death. Not to my knowledge.

Any ideas for fixing slimes in welcome. Let's discuss solutions.

Personally, I would vote for slimes to become vulnerable to other sources of damage. Such as Sec Tasers or Batons.

**Comment by Suhayll** [comment]
Ok so the heal bomb lowers even genetic damage.

**Comment by Vulpias** [comment]
okay 2 things. 

Firstly, Science has the tools to deal with Slimes. aka weapons, tazers and baton. 

Secondly, you can heal genetical dmg in the cryo tanks if I'm not mistaken. 

I'd need to look at the specific slime pages but I'm pretty sure slimes have natural weaknesses.

**Comment by Suhayll** [comment]
You can't heal genetic damage in cyro tanks if they are dead.

**Comment by KotetsuRedwood** [comment]
Slimes are not overpowered in xenobiology, since they're contained and expected to be there, and there's specific tools for dealing with them right there.(xeno stunbaton and xeno stunguns) It's also obvious when they're escaped (since they'll have broken their way out noisily.)

However, when they're randomly spawned in the station, all of these are not true. They could just be anywhere, you're not likely to have great weaponry against them, and you have no reason to expect them before the announcement.

"But what about fire extinguishers? Aren't slimes weak to those?"

Well, about that. Yeah, they _are_ weak to those. But, well... so are players. In order to attack slimes with fire extinguishers, you need to spray them. which makes tiles wet. And then players either need to walk, which makes it way easier for slimes to run up to them and stun them before latching on, or run, and slip, and then get latched on. 

"But what about non-slip shoes?"

What about them? They're rare, and you can't expect most players to have them. 

In short: **Slimes are only overpowered and difficult to fight when they're randomly spawned in hallways, or if you're an unskilled xenobiologist who's working xenobio for the first time.**

**Comment by AnonymousHybi** [comment]
> In short: Slimes are only overpowered and difficult to fight when they're randomly spawned in hallways, or if you're an unskilled xenobiologist who's working xenobio for the first time.

That's basically what Vale's going on about, @Vulpias I had an idea of making them weaker, lesser slimes which have a lot less health and less damage as a sub-type, this will then mean the slimes being spawned in via vents will be more balanced for a small variety of crew, especially since there's a lot of them too.

**Comment by Vulpias** [comment]
I played around with Making their overall damage lower and making them weaker in terms of healing. 

while being unable to make them weaker while they spawn I decided to make the slimes overall weaker, lowering their HP pools. 
seeing a Adult metal Slime has 350 HP
it requires more Discussion since I dont see this event as a event that slimes are op. Maybe make their weakness stronger while keeping theirs hp pools would be good but thats just my take. 

@Suhayll and @KotetsuRedwood what would you rather see. making the slimes weaker to water or lowering their overall Health pool, I'd like to test that out sometimes on the life server to see the changes first hand

**Comment by Vollybally** [comment]
Hmm. Looking back on this did we ever make any changes to this stuff? I'm just looking through issues that are currently open and seeing what we can close and what we can keep open.
