### ISSUE TITLE
Nerfed syringes sacrifice gameplay convenience for ""realism""

### ISSUE THREAD

**Issue by KotetsuRedwood** [CHOMPstation/CHOMPstation#22]
#### Brief description of the issue
Syringes significantly sacrifice gameplay convenience for some misguided attempt at ""realism"".

#### What you expected to happen
Not have to worry about syringes on top of everything else medical has to worry about when a patient comes in super injured

#### What actually happened
Someone decided "hey let's add more problems to medical!" and nerfed the fuck out of syringes in the name of """""""realism""""""" so now you've got to make sure you've always got like 60725 syringes on your person at all times.

#### Steps to reproduce
Step 1. Play Medical Doctor in a game set in the year 2562
Step 2. Have someone decide we should have syringes work the same as they do in 2016
Step 3. Remember that SS13 is ultimately a game and that the syringe nerf is ultimately busywork with no proper payoff purely based on """realism""".

#### Code Revision
Revision unknown
 
#### Anything else you may wish to add:
I've been playing medical for years and, from my experience, this is ultimately a nerf that serves no real purpose.
![tumblr_p4jhsi88sa1unu8zto1_500](https://user-images.githubusercontent.com/10330701/37444807-a592ce68-280b-11e8-80f0-df4e4c33480d.gif)

**Comment by KotetsuRedwood** [comment]
https://github.com/VOREStation/VOREStation/pull/3160 Here's the relevant changes for reverting

**Comment by Benemuel** [comment]
I kinda have to agree with the having them like MODERN day, especially since Self Sterilizing needles are a thing being worked on NOW just so real life doctors don't have to worry about that. And really, Hyposprays are becoming a thing to. If you REALLY want to make it more realistic, get rid of all the needles and have only hypos, because why are we using needles when we have the tech for that? Even if its because we are bumfuck nowhere, why can't SCIENCE make Hypos?

**Comment by KotetsuRedwood** [comment]
Closing this since it's fixed!
