### ISSUE TITLE
Request to add Coinpress to cargo

### ISSUE THREAD

**Issue by TomTyph** [CHOMPstation/CHOMPstation#99]
#### Brief description of the issue
Requesting to add a coinpress to Cargo/Mining.

The code for the coinpress is located at  https://github.com/CHOMPstation/CHOMPstation/blob/1fd65b1854583627805e63a2435d7f5942cdac62/code/modules/mining/mint.dm

The sprite file is in icons/obj/Stationobjs.dmi

**Comment by AnonymousHybi** [comment]
Would be nice if you added a object path instead of the path to the code..! Doesn't that much anyway, but other than that, yeah. It would be nice to put it in mining in one of the rooms like it used to back in 2015. And already exists in Paradise currently.

![image](https://user-images.githubusercontent.com/31137109/38330377-58667db8-3848-11e8-9b02-ea7742c963a6.png)

**Comment by TomTyph** [comment]
Forgive me, the object path is...from what i can tel..

/obj/machinery/mineral/mint
